# Generated by Django 5.2.5 on 2025-10-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler_frontend', '0003_onionsite_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='onionsite',
            name='threat_score',
            field=models.FloatField(default=0),
        ),
    ]
